name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Menjalankan pipeline saat ada perubahan di branch main
  pull_request:
    branches:
      - main   # Menjalankan pipeline saat ada pull request menuju branch main

jobs:
  # Job pertama: Build dan Test aplikasi
  build_and_test:
    runs-on: ubuntu-latest  # Menggunakan runner Ubuntu
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2  # Mengambil kode sumber dari repositori

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Tentukan versi Node.js yang digunakan

      - name: Install Dependencies
        run: |
          npm install  # Instal dependensi aplikasi

      - name: Run Tests
        run: |
          npm test  # Jalankan testing aplikasi untuk memastikan tidak ada error

  # Job kedua: Deploy aplikasi (contoh untuk aplikasi ke server atau platform)
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test  # Job deploy hanya dijalankan setelah build_and_test selesai
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH for Deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Gunakan kunci SSH untuk akses aman ke server

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server "cd /path/to/your/app && git pull && npm install && pm2 restart app"
        env:
          NODE_ENV: production
